# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - getting-started
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Call Jira Cloud Please!!
       
        run: | 
          echo Soo this is happening "$SEC" ${{secrets.SUPER_SECRET}}
          curl --request GET \
          --url 'https://${{ secrets.JIRA_CLOUD_SITE }}.atlassian.net/rest/api/3/project/WAR' \
          --user '${{ secrets.JIRA_CLOUD_USER }}:${{ secrets.JIRA_CLOUD_TOKEN }}' \
          --header 'Accept: application/json'

      - name: Create Issue
        if: "!contains(github.event.head_commit.message, 'WAR-')"
        run: |
          echo lets go!
    
          curl --request POST \
          --url 'https://${{ secrets.JIRA_CLOUD_SITE }}.atlassian.net/rest/api/3/issue' \
          --user '${{ secrets.JIRA_CLOUD_USER }}:${{ secrets.JIRA_CLOUD_TOKEN }}' \
          --header 'Accept: application/json'\
          --header 'Content-Type: application/json' \
          --data '{\
              "fields":{\
              "project":{\
                "id":"10042"\
              },\
              "issuetype":{\
                "id":"10002"\
              },\
              "components": [\
              {\
              "id": "10027"\
              }
              ],\
              "summary":"Postman"\
              }
              }'

        

